version: '3.7'

volumes:
    logs:
        driver: local
    dbdata:
        driver: local

networks:
    intern:

services:
    slim:
        image: eddiriarte/php-8.1
        working_dir: /var/www/html
        ports:
            - 8080:80
        environment:
            docker: "true"
        volumes:
            - .:/var/www/html
            - logs:/var/www/html/logs
        networks:
            - intern
    db:
        image: mysql:8
        platform: linux/x86_64
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: mysecretpassword
            MYSQL_ROOT_PASSWORD: mysecretpassword
            MYSQL_DATABASE: flixtrip
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - intern
